// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package rbac

import (
	"gitee.com/flycash/permission-platform/internal/repository"
	"gitee.com/flycash/permission-platform/internal/repository/dao"
	"gitee.com/flycash/permission-platform/internal/service/rbac"
	"gitee.com/flycash/permission-platform/internal/test/ioc"
)

// Injectors from wire.go:

func Init() *Service {
	db := ioc.InitDBAndTables()
	businessConfigDAO := dao.NewBusinessConfigDAO(db)
	businessConfigRepository := repository.NewBusinessConfigRepository(businessConfigDAO)
	resourceDAO := dao.NewResourceDAO(db)
	resourceRepository := repository.NewResourceRepository(resourceDAO)
	permissionDAO := dao.NewPermissionDAO(db)
	permissionRepository := repository.NewPermissionRepository(permissionDAO)
	roleDAO := dao.NewRoleDAO(db)
	roleRepository := repository.NewRoleRepository(roleDAO)
	roleInclusionDAO := dao.NewRoleInclusionDAO(db)
	roleInclusionRepository := repository.NewRoleInclusionRepository(roleInclusionDAO)
	rolePermissionDAO := dao.NewRolePermissionDAO(db)
	rolePermissionRepository := repository.NewRolePermissionRepository(rolePermissionDAO)
	userRoleDAO := dao.NewUserRoleDAO(db)
	userRoleRepository := repository.NewUserRoleRepository(userRoleDAO)
	userPermissionDAO := dao.NewUserPermissionDAO(db)
	userPermissionRepository := repository.NewUserPermissionRepository(userPermissionDAO)
	rbacRepository := repository.NewRBACRepository(businessConfigRepository, resourceRepository, permissionRepository, roleRepository, roleInclusionRepository, rolePermissionRepository, userRoleRepository, userPermissionRepository)
	service := rbac.NewService(rbacRepository)
	permissionService := rbac.NewPermissionService(rbacRepository)
	rbacService := &Service{
		Svc:           service,
		PermissionSvc: permissionService,
		Repo:          rbacRepository,
	}
	return rbacService
}

// wire.go:

type Service struct {
	Svc           rbac.Service
	PermissionSvc rbac.PermissionService
	Repo          repository.RBACRepository
}
