// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package abac

import (
	"gitee.com/flycash/permission-platform/internal/pkg/checker"
	"gitee.com/flycash/permission-platform/internal/repository"
	"gitee.com/flycash/permission-platform/internal/repository/dao"
	"gitee.com/flycash/permission-platform/internal/service/abac"
	"github.com/ego-component/egorm"
)

// Injectors from wire.go:

func Init(db *egorm.Component) *Service {
	resourceDAO := dao.NewResourceDAO(db)
	permissionDAO := dao.NewPermissionDAO(db)
	roleDAO := dao.NewRoleDAO(db)
	rolePermissionDAO := dao.NewRolePermissionDAO(db)
	roleInclusionDAO := dao.NewRoleInclusionDAO(db)
	userPermissionDAO := dao.NewUserPermissionDAO(db)
	userRoleDAO := dao.NewUserRoleDAO(db)
	businessConfigDAO := dao.NewBusinessConfigDAO(db)
	rbacRepository := repository.NewRBACRepository(resourceDAO, permissionDAO, roleDAO, rolePermissionDAO, roleInclusionDAO, userPermissionDAO, userRoleDAO, businessConfigDAO)
	policyDAO := dao.NewPolicyDAO(db)
	policyRepo := repository.NewPolicyRepository(policyDAO)
	environmentAttributeDAO := dao.NewEnvironmentAttributeDAO(db)
	resourceAttributeValueDAO := dao.NewResourceAttributeValueDAO(db)
	subjectAttributeValueDAO := dao.NewSubjectAttributeValueDAO(db)
	attributeDefinitionDAO := dao.NewAttributeDefinitionDAO(db)
	attributeValueRepository := repository.NewAttributeValueRepository(environmentAttributeDAO, resourceAttributeValueDAO, subjectAttributeValueDAO, attributeDefinitionDAO)
	attributeDefinitionRepository := repository.NewAttributeDefinitionRepository(attributeDefinitionDAO)
	attributeCheckerSelector := checker.NewCheckerBuilder()
	ruleParser := abac.NewRuleParser(attributeCheckerSelector)
	permissionSvc := abac.NewPermissionSvc(rbacRepository, policyRepo, attributeValueRepository, attributeDefinitionRepository, ruleParser)
	service := &Service{
		PermissionSvc:  permissionSvc,
		ValRepo:        attributeValueRepository,
		DefinitionRepo: attributeDefinitionRepository,
		PermissionRepo: rbacRepository,
		PolicyRepo:     policyRepo,
	}
	return service
}

// wire.go:

type Service struct {
	PermissionSvc  abac.PermissionSvc
	ValRepo        repository.AttributeValueRepository
	DefinitionRepo repository.AttributeDefinitionRepository
	PermissionRepo repository.RBACRepository
	PolicyRepo     repository.PolicyRepo
}
